version: "3.7"
services:
  db:
    image: mysql:8
    container_name: database_container
    ports:
      - 3306:3306
    volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
       - ./:/home/node/app
    environment:
        MYSQL_ROOT_PASSWORD: 'library'
        MYSQL_DATABASE: 'library'
        MYSQL_USER: 'lib'
        MYSQL_PASSWORD: 'library'
  node:
    image: "node:12"
    user: "root"
    container_name: node_container
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 8081:3000
    command: bash -c "npm install ; npm install -g nodemon && nodemon index"
    # command: bash -c "nodemon index"
    depends_on:
      - db
